FROM centos
#version  jdk 1.7 
MAINTAINER mo
ENV JAVA_HOME /opt/uuzz/java
ENV PATH $JAVA_HOME/bin:$PATH
RUN \
	echo "JAVA_HOME=\"/opt/java/jdk1.7.0_79/\"" > /etc/profile.d/jdk.sh && \
	echo "PATH=\"\$JAVA_HOME/bin:\$PATH\"" >> /etc/profile.d/jdk.sh
ADD jdk-7u79-linux-x64.tar.gz /opt/java

